# FUNDING DISABLED
# This file intentionally disables all funding options
# This is a personal learning project with no donation intentions
# Not affiliated with the original Suroi project or its funding

# All funding platforms are intentionally left empty or commented out
# github:
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
# buy_me_a_coffee:
# thanks_dev:
# custom:
